### PR TITLE
adding proper benchmarking protocol by waiting for current and previo…

### PR DESCRIPTION
**Pull request by soumith**
…us computation to finish

without this, there is a chance that benchmark numbers are incorrect

### CODE REVIEW

**Review by arrufat — COMMENTED** [review]
Thank you for the PR, when I add this, the computation time goes up from 6 to 200 ms. Now I am wondering if I am doing it right on the dlib side, since it's less than 1 ms.

Edit:
Also, I noticed that, after this change, the inference time depends on the batch size, which makes me think there's some data transfer going on. The times I get are similar to the ones I get with dlib when measuring:
``` c++
net.subnet().forward(x);
dlib::resizable_tensor y = net.subnet().get_output();
x.host();
```
And from dlib's [documentation](http://dlib.net/dlib/cuda/tensor_abstract.h.html#host), 

> a call to `host()` copies the data from the device to the host, while this is happening the call to host() blocks.

But nothing in the PyTorch [documentation](https://pytorch.org/docs/stable/cuda.html#torch.cuda.synchronize) says anything about copying data. Curiously, if I add `x.cpu()` after `torch.cuda.synchronize()` the times are the same.

**Comment by soumith** [comment]
CUDA API is asynchronous. So, issuing a function call does not mean the processing is finished. You have to wait for the processing to be finished.
This is a property of CUDA API and is same with dlib or pytorch.

If you want to confirm, first in your terminal, set this environment flag: `export CUDA_LAUNCH_BLOCKING=1`, and then run your dlib or pytorch program.

These will give you the real synchronized times.

**Comment by soumith** [comment]
more info https://stackoverflow.com/questions/4729852/disabling-all-asynchronous-execution-in-cuda-programs

**Comment by arrufat** [comment]
Thanks for the information, I've updated the code to set that environment variable and updated the tables, have a look and let me know if you think this PR still applies.

**Pull request closed without merging**
